apiVersion: v1
kind: ConfigMap
metadata:
  name: omni-config
  namespace: default
data:
  # Kafka
  KAFKA_BROKERS: "kafka:9092"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # JWT
  JWT_SECRET: "omni_super_secret_change_me"
  JWT_EXPIRES_IN: "1d"

  # OpenTelemetry → Jaeger
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"

  # Log
  LOG_LEVEL: "info"

  # Auth DB
  AUTH_DB_HOST: "auth-db"
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: "auth"
  AUTH_DB_PASS: "auth_pass"
  AUTH_DB_NAME: "auth_db"

  # Product DB
  PRODUCT_DB_HOST: "product-db"
  PRODUCT_DB_PORT: "5432"
  PRODUCT_DB_USER: "product"
  PRODUCT_DB_PASS: "product_pass"
  PRODUCT_DB_NAME: "product_db"

  # Order DB
  ORDER_DB_HOST: "order-db"
  ORDER_DB_PORT: "5432"
  ORDER_DB_USER: "order"
  ORDER_DB_PASS: "order_pass"
  ORDER_DB_NAME: "order_db"

  # Payment DB
  PAYMENT_DB_HOST: "payment-db"
  PAYMENT_DB_PORT: "5432"
  PAYMENT_DB_USER: "payment"
  PAYMENT_DB_PASS: "payment_pass"
  PAYMENT_DB_NAME: "payment_db"
